route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "email-me"
receivers:
  - name: "web.hook"
    webhook_configs:
      - url: "http://127.0.0.1:5001/"
  - name: email-me
    email_configs:
      - to: EMAIL_YOU_WANT_TO_SEND_EMAILS_TO
        from: YOUR_EMAIL_ADDRESS
        smarthost: smtp.gmail.com:587
        auth_username: YOUR_EMAIL_ADDRESS
        auth_identity: YOUR_EMAIL_ADDRESS
        auth_password: YOUR_EMAIL_PASSWORD
inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
